apiVersion: 1

datasources:
  - name: Prometheus
    # uid must match the "uid":"prometheus" referenced in dashboards/*.json
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
